### ISSUE TITLE
Wrong delete where params

### ISSUE THREAD

**Issue by aslubsky** [fremail/sequelize-nested-set#14]
Look like you have a bug in delete method here https://github.com/fremail/sequelize-nested-set/blob/master/index.js#L888
1) using `await this.destroy(dOptions);` insted of `await Model.destroy(dOptions);` now generate sql `DELETE FROM `tableName` WHERE `id` = 123`
2) using `dOptions.where.lft` in same where params will generate sql only for last param, like 
`DELETE FROM `tableName` WHERE `lft` <= 10 AND `tree_key` = 1`
I've prepared PR, pls check

**Comment by fremail** [comment]
Thank you @aslubsky for reporting the issue and fixing it!

I merged your PR and released v.1.4.0 so your fix is already published 🎉
