### ISSUE TITLE
how to use for sequelize-typescript？

### ISSUE THREAD

**Issue by SolidZORO** [fremail/sequelize-nested-set#21]
sequelize-typescript https://github.com/RobinBuschmann/sequelize-typescript

**Comment by fremail** [comment]
@SolidZORO thank you for the question, but I don't know because I see sequelize-typescript first time :) 
If you have ideas, please feel free to post them here and do a PR.

**Comment by SolidZORO** [comment]
Hi, I'm also trying now, and I'll update here or PR if I have results.

**Comment by SolidZORO** [comment]
e.g. Nest.js + sequelize-typescript

```
import nestedSet from 'sequelize-nested-set';

@Injectable()
export class CategoryService {
  constructor(
    @InjectModel(Category) private readonly categoryRepo: typeof Category,
    @InjectConnection() private sequelizeConnection: any,
  ) {
    this.categoryRepo = nestedSet(this.categoryRepo, this.sequelizeConnection);
  }
}
```

After completing it I found that I couldn't recursively classify it.  https://github.com/fremail/sequelize-nested-set/issues/13  Just gave up using it. 😭
