### ISSUE TITLE
parentId

### ISSUE THREAD

**Issue by ivan-ionin** [fremail/sequelize-nested-set#6]
Maybe worth adding **parentId** field (like **pid** or **pnt**) to interface for simplify usage tree nodes?

**Comment by fremail** [comment]
Interesting idea, @ivan-ionin! I have no objection!

We could add the field as an optional.

PR is welcome :)

**Comment by ustun** [comment]
+1 Baum for PHP seems to have that as well. See https://github.com/etrepat/baum
