### ISSUE TITLE
Cannot insert the node that has its place in the tree

### ISSUE THREAD

**Issue by Gn0ume** [fremail/sequelize-nested-set#7]
Hey man! Can't get how to use addChild method? I can successfully add roots but when I do
```
.then(model=>{
model.addChild(new Model({...})
})
```
I always get this error `Cannot insert the node that has its place in the tree`

What I do wrong?

**Comment by fremail** [comment]
@Gn0ume thank you for reporting the bug! 

Found similar bug with these functions:
- insertAsLastChildOf
- insertAsFirstChildOf
- insertAsNextSiblingOf
- insertAsPrevSiblingOf
- insertAsParentOf

I'm working on a fix for the listed functions

**Comment by fremail** [comment]
@Gn0ume sequelize-nested-set@1.1.3 with the fixes was released!
